apiVersion: 1
datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
      derivedFields:
        # 从 trace_id 直接跳转到 Tempo 溯源
        - name: trace_id
          matcherRegex: 'trace_id":\s*"([0-9a-f]{32})'
          url: "$${__value.raw}"
          datasourceUid: "tempo"

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"